{
  "comments": [
    {
      "key": {
        "uuid": "e17c1458_a91caec4",
        "filename": "src/main/java/com/googlesource/gerrit/plugins/renameproject/database/DatabaseRenameHandler.java",
        "patchSetId": 35
      },
      "lineNbr": 198,
      "author": {
        "id": 1012732
      },
      "writtenOn": "2019-10-16T19:51:28Z",
      "side": 1,
      "message": "And we don\u0027t know why. Can \u0027ex\u0027 information be added to this trace?\n\nOr, below, \u0027e\u0027 is thrown also in this case. Re-throw \u0027ex\u0027 instead? But then, we lose \u0027e\u0027 information since it is not part of line 192\u0027s trace. Can we chain the exceptions?",
      "range": {
        "startLine": 198,
        "startChar": 8,
        "endLine": 198,
        "endChar": 55
      },
      "revId": "4f1caecf120ea1ab3928bcdd5c8924f50609ee72",
      "serverId": "173816e5-2b9a-37c3-8a2e-48639d4f1153",
      "unresolved": true
    },
    {
      "key": {
        "uuid": "521c8491_0bb51031",
        "filename": "src/main/java/com/googlesource/gerrit/plugins/renameproject/database/DatabaseRenameHandler.java",
        "patchSetId": 35
      },
      "lineNbr": 198,
      "author": {
        "id": 1083195
      },
      "writtenOn": "2019-10-16T22:57:35Z",
      "side": 1,
      "message": "I did that in the follow up change. I can bring it back here if you see that is necessary.",
      "parentUuid": "e17c1458_a91caec4",
      "range": {
        "startLine": 198,
        "startChar": 8,
        "endLine": 198,
        "endChar": 55
      },
      "revId": "4f1caecf120ea1ab3928bcdd5c8924f50609ee72",
      "serverId": "173816e5-2b9a-37c3-8a2e-48639d4f1153",
      "unresolved": false
    }
  ]
}